name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Usar Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Autenticación con Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t pokedex-angular .

      - name: Save Docker image as tar
        run: docker save pokedex-angular -o pokedex-angular.tar

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: 'pokedex-angular.tar'
          target: '~/'

      - name: Deploy on Azure VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            docker load -i ~/pokedex-angular.tar
            docker stop pokedex-angular || true
            docker rm pokedex-angular || true
            docker run -d --name pokedex-angular -p 80:80 pokedex-angular
