name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    timeout-minutes: 30
    environment: azure

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t pokedex-angular:${{ github.sha }} -t pokedex-angular:latest .

      - name: Save and compress Docker image
        run: docker save pokedex-angular:${{ github.sha }} | gzip > pokedex-angular.tar.gz

      - name: Copy Docker image to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: 'pokedex-angular.tar.gz'
          target: 'deployments'
          timeout: 10m

      - name: Deploy on Azure VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          command_timeout: 10m
          script: |
            set -e
            cd ~/deployments

            # Decompress and load image
            gunzip -c pokedex-angular.tar.gz | docker load

            # Stop and remove old container
            docker stop pokedex-angular 2>/dev/null || true
            docker rm pokedex-angular 2>/dev/null || true

            # Deploy new container with SSL support
            docker run -d \
              --name pokedex-angular \
              --restart unless-stopped \
              --expose 80 \
              -e VIRTUAL_HOST=pokedex.hanscastellar.com \
              -e LETSENCRYPT_HOST=pokedex.hanscastellar.com \
              -e LETSENCRYPT_EMAIL=hans@ejemplo.com \
              pokedex-angular:${{ github.sha }}

            # Wait for container to start
            sleep 5

            # Verify container is running
            sleep 3
            CONTAINER_STATUS=$(docker inspect -f '{{.State.Status}}' pokedex-angular 2>/dev/null || echo "not found")

            if [ "$CONTAINER_STATUS" != "running" ]; then
              echo "❌ Container status: $CONTAINER_STATUS"
              echo "Container logs:"
              docker logs pokedex-angular 2>&1 || true
              exit 1
            fi

            echo "✅ Container is running successfully"

            # Cleanup
            rm -f pokedex-angular.tar.gz
            docker image prune -f

            echo "Deployment successful!"

      - name: Cleanup local artifacts
        if: always()
        run: rm -f pokedex-angular.tar.gz
